---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/network/ingress-nginx/chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: cert-manager-chart
