---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-16-nightly
  namespace: database
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: postgresql-16
  immediate: true
