---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-16
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2-13
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
  superuserSecret:
    name: cloudnative-pg-superuser
  enableSuperuserAccess: true
