---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '3.3.2'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: ghcr.io/miniflux/miniflux
              tag: 2.2.0
            env:
              RUN_MIGRATIONS: '1'
              CREATE_ADMIN: '1'
              BASE_URL: https://miniflux.cluster.dnhrrs.xyz
              OAUTH2_PROVIDER: oidc
              OAUTH2_REDIRECT_URL: https://miniflux.cluster.dnhrrs.xyz/oauth2/oidc/callback
              OAUTH2_OIDC_DISCOVERY_ENDPOINT: https://auth.cluster.dnhrrs.xyz/application/o/miniflux/
              OAUTH2_USER_CREATION: '1'
            envFrom:
              - secret: miniflux-credentials
    service:
      app:
        controller: app
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: nginx
        hosts:
          - host: miniflux.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
