---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 5m
  path: ./terraform/roots/postgresql
  approvePlan: auto
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tf-controller-cli-config
    namespace: flux-system
  vars:
    - name: postgres_host
      value: postgresql.database.svc.cluster.local
  varsFrom:
    - kind: Secret
      name: tf-postgresql-vars
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  runnerPodTemplate:
    spec:
      volumeMounts:
        - name: sops
          mountPath: /home/runner/.config/sops/age
      volumes:
        - name: sops
          secret:
            secretName: tf-controller-sops
