apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pdns-credentials
stringData:
    api-key: ENC[AES256_GCM,data:E+ynu4mlmw6Cn/wbkRuFJGk6nWE6Eua3b7OTTLQzfK0=,iv:AJhOCK0mzWSWN24vxAMzux8xqADm5kY7pWSdc98Uzus=,tag:H7/qOQzc0Smlre/q5Gohdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMnY0M3hUTFdMajNjUmlJ
            M2JIaVBNdldTM2czY0JZd0Vja2xJSC9EczAwCjF5K2ViRUNWdms3TThvY3cvbVZD
            TVdyYU0zczN4eTBqOWdkcE1WQjVvUWMKLS0tIHpLVzBGdFg5aDZoeWFrNnJSZGpR
            Z2djRW5oWENHOTVjekNSeVowaXgySXMK5PmIWw08iEvqyBW6/RJ29f7ySInyWiM7
            DVEOdRUbwKDOXi0TNs5N94CyoeUla/2tE35xgkm94b+5xr8pJwyP6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T19:01:55Z"
    mac: ENC[AES256_GCM,data:67S8QBWT+taDxDPWrz84lB9Dbe3xWVldQARjpEBQuZfMMQ/U1WXeO8GRsLgVcRPo5Wczb+7pStofVmPXxDU4ryyfS0PAGMT13AHcqlbC5qkaTwtaaJj3Nrgxo9AesE3Sll5po7ExF+bJW6Rv3ayVC3nZx4RLeEFG2rjYurnxRuI=,iv:eBrNW1pM4TSDnwSXdEanXKZqyhR0G379vmhwuVJJslw=,tag:LOZq8lyfbmQcDXzvbtx2DA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
