apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:yyoxCzQ8sGtJOFwBTL2+3/wbx9hW8oQmtHzD9ETaGX9W+lO9tK9/SpTNBe974f5m8x7RfllKynZY7r293Hw7Qo++3Gem8/LwCXBbAf0/t0qwnaYDryajCUmt5SOEKPz0Ohec3LJHrhqWGF0iZeSgg+AdxGhsb8uOAlHF4080IHlFdqZT7XkNh0v/rdvY42kr,iv:Dk1IDb4eVCP3mjZdBHSEV20LktcIbPz8Nj3amjtcZSM=,tag:hS62aoIGyfM5/tQeqt6D0g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authentik-credentials
    namespace: authentik
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YzdhMTcvYm81ckI5MDNw
            Q2w0U0xnMUxBNEtDQjcwRW5vN2h0SUlOcEhvCjNUcmZpa0w4dGd4aW9wb1hYUGZK
            c1pleXROcllFVkxiUExhU1hUa2RUOTgKLS0tIHVIR1BKaC9wSzAvSUNpWk5KbEk1
            QmhPVVBVMjRBODYraWdVZEZ0cDBsRGsKVcce6hnNAsicCP4+nT9P2Owr7yzbMqRj
            0eP/t+CbilB70n7oM2L50pfbTU2ciOP1l3/125mdbb2ZJfZH7lpOeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-16T12:51:57Z"
    mac: ENC[AES256_GCM,data:aPpVoghOBF5IX7clt2Y1P0ST7SchlFUkLhxCxPG+Y2QpsHJE7t8DmhhemD0R/T22plFu5eDuUAGkw5alJXE1P+l+339iNwEjkJPQrQ+xX3d/7CrdwENSQQeFzEnCgnvr5njeeg9VJlfolud3RGoN+tfXtN+K7ZwB/GC/6GoSYXc=,iv:HxP1RpNzoUucNf2y0Qh/ErroQ+gfgxPttDL8ZM8M7Dc=,tag:ym7Fh2FJonm9umacs3RwXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
