---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: '2022.7.3'
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2022.12.2
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      hosts:
        - host: auth.dnhrrs.xyz
          paths:
            - path: '/'
              pathType: Prefix
      tls:
        - secretName: authentik-cert
          hosts:
            - auth.dnhrrs.xyz
    authentik:
      postgresql:
        host: postgresql.database.svc.cluster.local
        name: authentik
        user: authentik
    redis:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: authentik-credentials
