---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
  namespace: authentik
spec:
  ingressClassName: nginx
  rules:
    - host: photoprism.dnhrrs.xyz
      http:
        paths:
          - backend:
              service:
                name: authentik
                port:
                  number: 80
            path: /outpost.goauthentik.io
            pathType: Prefix
