---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
  namespace: authentik
spec:
  rules:
    - host: photoprism.dnhrrs.xyz
      http:
        paths:
          - backend:
              serviceName: authentik
              servicePort: 80
            path: /outpost.goauthentik.io
