---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: '0.14.6'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
