apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:k+EVW2GSBLgtH83uKSGSMgBxW+LYLWU9uDnYck73UyHIF1OsrYJFbOLb/J8=,iv:hYI0KY7LQh9G1SjROG6OPtJmbX/Y1Wwa5Kalhw6at4I=,tag:ISRwU3Mi7OvJxQ9JTZbGlA==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:FmIqSsBqbt25kM/K/TsZPjuYd190YXYBhULBz/Ac4xYyrGRMPW7RyapZNgMV2Bi+TqnO568SvFm2TZ6KgVT+YoDrvlUQ0Hbq4QR4pDxdRmNZwdqXiQvvhW3ZEEZTMy0CzTS9PcAe8go+d8yDupcXrp/vEl6EjctPqCUBtOEzKP8lRJkEXRDD4z8oDH6nrQ6xuDNrqbDGLzPXDQ3RupYQ5aKYVh2LWZMtqa1JAw==,iv:nsWXFCS5Eo9VWN3lxoOYV9mzfPOW61SjCiaggOEBwAc=,tag:sY4/NR4o2HEgeyi/RX8tUA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:PXTikLZrVXiYjp46BMAwqifsnjU3hA1MhJLXGQpbN9S+RzdJl9fQP3FOeD4L68MCS1bgcyUodiM=,iv:TcNW8a0yzvnRvplYaEnTosHalWDfB9GLqfYTm3TgX/o=,tag:9MQxKBM2W1V4I3Mc34Kcgg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:4qmt1r0XQHAdeamET0q3wygfSVR9qFnnxOiZr+CUUut7tDvlopJorVzxjwfOFPg6l8WlHHZ5k4wNPMtEB3vUnuKkhpK6i5eMHwbSpd4b0/64xOpyNilhyEN6EBlhPLOj26076azLgQ4ptjWg5BKB24tdS4k0xAPxGRb5uV+5gYZya9pcVwTj0MyOqoHR2jL89ewpiTMq5nQe6GM8NXJqPFbSBTCrf1itGMxYOg==,iv:qNL5tenN8z6SsSr+zxm+W65BQuZ7VIYOYjgZpUnqmes=,tag:X99KkCqrMkkujlvCUvLguA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kitchenowl-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORjk1cGh2MWZQbytMUzB0
            ZldUZXFCZ0RSUmsvVmJVTnZCTmZKTm9PNFdNCjJpbmNtTkVXT3JlanQ2MUFZV25C
            S2ZEWmxRckZCY1RZRlNGemNvemtEK0UKLS0tIDFwZ29VVktOT0hjOVpmM1l6N3px
            Q3BKQ2laTXhMYWFXMmZydVZSQ1k0d0UKZnfLM6MWwHnF4nQ0ECmw1NKz8N/vTA/N
            ng9u5iastVqVh76pBEeomZ/xlYMnxyLsHMEfC/ZQl4Kc01UUGNncjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T19:14:57Z"
    mac: ENC[AES256_GCM,data:0r7kqLCkVBgQkQOJRHsrZocA8b7E7UsPByta16kL6aSchN/ZIumPaCmK3qI+6ACO1osPjJt0OcJTEsdMzuhc6nOJPuCsTkXLBM7gn2EeCwXtjMcW0QCCVbYEkTcMz/DQpDd/prMM34IKUwi2fzl7qqKFBFA/rydXqoxOies8uyY=,iv:YLTrSywCInD5vlVjboAK/L9GVmHOBoCQiOtrbLWgu4M=,tag:5DAX1S2joX6hkmTVLmWmQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
