---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: photoprism
      version: '6.3.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: photoprism/photoprism
      tag: '20220121'
    env:
      PHOTOPRISM_READONLY: 1
      PHOTOPRISM_WORKERS: 1
      PHOTOPRISM_SITE_URL: https://photoprism.dnhrrs.xyz/
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/auth-url: |-
            http://authentik.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://photoprism.dnhrrs.xyz/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        ingressClassName: nginx
        hosts:
          - host: photoprism.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: photoprism-cert
            hosts:
              - photoprism.dnhrrs.xyz
    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        existingClaim: photoprism
      originals:
        enabled: true
        mountPath: /photoprism/originals
        existingClaim: photos
    resources:
      requests:
        cpu: 1000m
        memory: 0.5Gi
      limits:
        cpu: 2000m
        memory: 1.5Gi
