---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 5m
  path: ./terraform/roots/authentik
  approvePlan: auto
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tf-controller-cli-config
    namespace: flux-system
  vars:
    - name: authentik_url
      value: http://authentik.authentik.svc.cluster.local
  varsFrom:
    - kind: Secret
      name: tf-authentik-vars
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  runnerPodTemplate:
    spec:
      volumeMounts:
        - name: sops
          mountPath: /home/runner/.config/sops/age
      volumes:
        - name: sops
          secret:
            secretName: tf-controller-sops
