---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: photos-web
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/photos-web/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
