---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: jellyfin
      version: '9.1.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      tag: '10.7.7'
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: nginx
        hosts:
          - host: jellyfin.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: jellyfin-cert
            hosts:
              - jellyfin.dnhrrs.xyz
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: nfs-client
      cache:
        enabled: true
        mountPath: /cache
        storageClass: nfs-client
      media:
        enabled: true
        mountPath: /media
        existingClaim: dvds
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 3000m
        memory: 4096Mi
