---
keys:
  - &dan age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
  - &lumia age1ued9ufgfwkrx00n3vmneae6grex4r0nuuytnwdk63u62flga4u5s9kd20j
creation_rules:
  - path_regex: talos/.*\.ya?ml
    encrypted_regex: ^(crt|id|key|secret|secretboxEncryptionSecret|token)$
    age: *dan
  - path_regex: (flux|kubernetes)/.*\.ya?ml
    encrypted_regex: ^(data|stringData)$
    age: *dan
  - path_regex: nixos/.*/secrets\.yml
    key_groups:
      - age:
          - *dan
          - *lumia
  - age: *dan
