---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recipes-site
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/recipes-site/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
