---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '3.5.1'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: '2024.10.2@sha256:a6b2a25a4ae7d747506ad3a24bcaf1ee2290fb82811f077447b8847eecd29c56'
            env:
              TZ: Europe/London
    service:
      app:
        controller: app
        ports:
          http:
            port: 8123
    ingress:
      app:
        className: nginx
        hosts:
          - host: hass.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: home-assistant
