---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '4.1.2'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        pod:
          hostNetwork: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: '2025.7.4@sha256:e5bf3905955081dc4aae3b3980870c43ce6d8ffb880b5447addb3b3ba00f7bc0'
            env:
              TZ: Europe/London
    service:
      app:
        controller: app
        ports:
          http:
            port: 8123
    ingress:
      app:
        className: nginx-internal
        hosts:
          - host: hass.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: home-assistant
