---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/storage/csi-driver-nfs/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
