---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: bookstack
      version: '3.1.1'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      tag: version-v21.05.4
    env:
      DB_HOST: cluster-97bc32.db.dnhrrs.xyz
      DB_USER:
        valueFrom:
          secretKeyRef:
            name: bookstack-credentials
            key: user
      DB_PASS:
        valueFrom:
          secretKeyRef:
            name: bookstack-credentials
            key: password
      DB_DATABASE: bookstack
      APP_URL: https://bookstack.dnhrrs.xyz
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hosts:
          - host: bookstack.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: bookstack-cert
            hosts:
              - bookstack.dnhrrs.xyz
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: bookstack
