---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstack
  namespace: default
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
