---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: recipes-site
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes-site
  template:
    metadata:
      labels:
        app: recipes-site
    spec:
      containers:
        - name: recipes-site
          image: 'gitea.dnhrrs.xyz/dan/recipes:0.2.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi

---
kind: Service
apiVersion: v1
metadata:
  name: recipes-site
  namespace: default
spec:
  selector:
    app: recipes-site
  ports:
    - name: http
      port: 80
      containerPort: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: recipes-site
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: recipes.dnhrrs.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recipes-site
                port:
                  name: http
  tls:
    - secretName: recipes-site-cert
      hosts:
        - recipes.dnhrrs.xyz
