---
- name: List zone records
  command:
    argv:
      - pdnsutil
      - list-zone
      - "{{ _pdns_zone }}"
  register: pdns_zone_output
  changed_when: false
- name: Register record
  command:
    argv:
      - pdnsutil
      - add-record
      - "{{ _pdns_zone }}"
      - "{{ _pdns_name }}"
      - "{{ _pdns_type }}"
      - "{{ _pdns_content }}"
  when: "_pdns_name ~ '.' ~ _pdns_zone not in pdns_zone_output.stdout"
