---
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - pdns-server
    - pdns-backend-sqlite3
    - sqlite3

- name: Install config
  ansible.builtin.template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
    owner: pdns
    group: pdns
    mode: 0640
  notify: Restart pdns

- name: Create database
  ansible.builtin.shell:
    cmd: "sqlite3 {{ pdns_database }} < {{ pdns_schema }}"
    creates: "{{ pdns_database }}"

- name: Set permissions on database
  ansible.builtin.file:
    path: "{{ pdns_database }}"
    owner: pdns
    group: pdns
    state: file

- name: Enable service
  ansible.builtin.service:
    name: pdns
    state: started
    enabled: true
