---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pdns_packages }}"
- name: Install config
  template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
    owner: pdns
    group: root
    mode: 0640
  notify: Restart pdns
- name: Create database
  shell:
    cmd: "sqlite3 {{ pdns_database }} < {{ pdns_schema }}"
    creates: "{{ pdns_database }}"
- name: Set permissions on database
  file:
    path: "{{ pdns_dir }}"
    owner: pdns
    group: pdns
    state: directory
    recurse: true
- name: Enable service
  service:
    name: pdns
    state: started
    enabled: true
