---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s-gateway
      version: '2.4.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  values:
    image:
      registry: quay.io
      repository: oriedge/k8s_gateway
      tag: v0.4.0
    domain: cluster.dnhrrs.xyz

