---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-red
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/home/node-red/app
  prune: true
  wait: true
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: homelab

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-red-volsync
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/volsync-system/volsync/template
  prune: true
  wait: true
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: homelab
  postBuild:
    substitute:
      APP: node-red
      CAPACITY: 1Gi
      DELAY: "2"
