---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: '2.5.5'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    controller:
      image:
        repository: bitnami/metallb-controller
        tag: 0.10.2-debian-10-r64
    speaker:
      image:
        repository: bitnami/metallb-speaker
        tag: 0.10.2-debian-10-r68
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 10.23.20.90-10.23.20.99
