---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkwarden
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/linkwarden/app
  prune: true
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkwarden-volsync
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/volsync-system/volsync/template
  prune: true
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab
  postBuild:
    substitute:
      APP: linkwarden
      CAPACITY: 10Gi
      DELAY: "6"
