---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.cluster.dnhrrs.xyz
    admin:
      existingSecret: grafana-credentials
      userKey: adminUsername
      passwordKey: adminPassword
    grafana.ini:
      server:
        root_url: https://grafana.cluster.dnhrrs.xyz
      database:
        type: postgres
        host: postgresql-16-rw.database.svc.cluster.local:5432
        name: grafana
        user: grafana
      auth.generic_oauth:
        enabled: true
        auth_url: https://auth.cluster.dnhrrs.xyz/application/o/authorize/
        api_url: https://auth.cluster.dnhrrs.xyz/application/o/userinfo/
        token_url: https://auth.cluster.dnhrrs.xyz/application/o/token/
        scopes: user email profile
        role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
    envFromSecret: grafana-env
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            access: proxy
            isDefault: true
