---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
stringData:
  RESTIC_REPOSITORY: s3:${VOLSYNC_R2_BASE}/${APP}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_R2_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_R2_SECRET_ACCESS_KEY}
