---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${CAPACITY}
  storageClassName: ${STORAGE_CLASS:=nfs-csi}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${APP}-rdst
