apiVersion: v1
data:
    database: ENC[AES256_GCM,data:NHi3R/cmw3B4+UCJau7LcRoYiSRYyrsw,iv:80ljxrW+nVjGkn1BRwxzNjt2z6IhgK2x0VjgJBFboBo=,tag:1QxH9WaJ6hgOqvGQzfVD5g==,type:str]
    secret: ENC[AES256_GCM,data:/4h2q13ILmNT11ZLPXGGtn8LvfYQH5p3dqnl+Rp08aLw7+2xcwb/Z+uUJW8=,iv:iEgf7MP+smR7k2rBoEmv1HwLZS94v1EFx8uxu1ApjLg=,tag:v2auhBK3KjvXxcqA8jWVSw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authentik-credentials
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVczAyczA0TGNWVUhEZm5O
            Lys2NmNrR2tPOFVXRllKZFJRWlFFWFdBMEZFCm5TeE1jTUg0TWY4NnlUQzRFSk9M
            MURRL1lNc0xiaUQ1Y3p0YXpGbTFhd0kKLS0tIHBiRWQ2dnNNV0hkRHlQVlJ0WkNC
            d3FzcXlwSXZiRlo1NVppVFVqK3hsSnMKSjKmGGI1GE7hfDWNXubRbXPqgNLb2Uhk
            H9oQfrJQmpDC3PiAv0//v8tOhL74AX7PzWezw430pzq0SJzEKssIwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T19:45:04Z"
    mac: ENC[AES256_GCM,data:yoVz/X1N4e7UCcpL9Bep1T7DOMG7MHNuQoOHYnt6ypHkGwwDonHzC6719F2HTAPR/cVzjvy/jXw0h3kKiB4PInDzgCJEkDo5cmVjmdfmPr0PskqROqIy3Z7gVJIZsi0WJ8GzLUpLZ5cdqyI+c/W/TNnwmd2QZRv1oexIppiLpx0=,iv:YXks4xIZ+Fk6EselhR8/uFH+qB/TLaX19YviRUln4N0=,tag:ZXFfDnUSa91W5CI0Ao8Ing==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
