---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: '2024.2.2'
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
  values:
    server:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2024.2.2
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: nginx
        hosts:
          - auth.cluster.dnhrrs.xyz
        paths:
          - /
        pathType: Prefix
        tls:
          - secretName: authentik-cert
            hosts:
              - auth.cluster.dnhrrs.xyz
    authentik:
      postgresql:
        host: postgresql-16-rw.database.svc.cluster.local
        name: authentik
        user: authentik
    redis:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: authentik-credentials
