---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: '2024.8.0'
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - auth.cluster.dnhrrs.xyz
        paths:
          - /
        pathType: Prefix
    authentik:
      postgresql:
        host: postgresql-16-rw.database.svc.cluster.local
        name: authentik
        user: authentik
    redis:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: authentik-credentials
      valuesKey: secret
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-credentials
      valuesKey: database
      targetPath: authentik.postgresql.password
