apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:k+EVW2GSBLgtH83uKSGSMgBxW+LYLWU9uDnYck73UyHIF1OsrYJFbOLb/J8=,iv:hYI0KY7LQh9G1SjROG6OPtJmbX/Y1Wwa5Kalhw6at4I=,tag:ISRwU3Mi7OvJxQ9JTZbGlA==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:FmIqSsBqbt25kM/K/TsZPjuYd190YXYBhULBz/Ac4xYyrGRMPW7RyapZNgMV2Bi+TqnO568SvFm2TZ6KgVT+YoDrvlUQ0Hbq4QR4pDxdRmNZwdqXiQvvhW3ZEEZTMy0CzTS9PcAe8go+d8yDupcXrp/vEl6EjctPqCUBtOEzKP8lRJkEXRDD4z8oDH6nrQ6xuDNrqbDGLzPXDQ3RupYQ5aKYVh2LWZMtqa1JAw==,iv:nsWXFCS5Eo9VWN3lxoOYV9mzfPOW61SjCiaggOEBwAc=,tag:sY4/NR4o2HEgeyi/RX8tUA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kitchenowl-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORjk1cGh2MWZQbytMUzB0
            ZldUZXFCZ0RSUmsvVmJVTnZCTmZKTm9PNFdNCjJpbmNtTkVXT3JlanQ2MUFZV25C
            S2ZEWmxRckZCY1RZRlNGemNvemtEK0UKLS0tIDFwZ29VVktOT0hjOVpmM1l6N3px
            Q3BKQ2laTXhMYWFXMmZydVZSQ1k0d0UKZnfLM6MWwHnF4nQ0ECmw1NKz8N/vTA/N
            ng9u5iastVqVh76pBEeomZ/xlYMnxyLsHMEfC/ZQl4Kc01UUGNncjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T18:58:28Z"
    mac: ENC[AES256_GCM,data:0roS/oJfyXMCZhQWSbOwmMvJ+Mv09MmMEr/7CSqRlpQ2vKVV4rc708wofzwDCaGOIvWTERJABApPEnDzTjlz7nz5UOErmIc1RDJuirbtzUr662q3oit6h4fcmQY7c0iMLpXVkLbxmRdALBd07U4IkRbTptLQL9Tc/33b+bM8Geo=,iv:tqxMo9MRhDWPXClYmpTlBhyYBZmKhdajrjzIswO3r9E=,tag:qyrOzL/lTSFZV1GWdT4n1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
