apiVersion: v1
data:
    database: ENC[AES256_GCM,data:keiQxQ0oeF7U2ss3pJdJSl2Hb3bwCaeaI4Nk1Qe4YJZxfCYQXSyuVw9mFJw=,iv:Uc4pEQeqgYdGLYFp9gfi+gjic5ibp2mDRTZmL9/pOZs=,tag:GQhtP7NVQAGuFRyWYKDnNw==,type:str]
    password: ENC[AES256_GCM,data:95D01KCzGklzvJGnRmDJVdlF1Crr9Z2H1314JKA78k2EHgrkaDmc2gR9jlo=,iv:oOGQd0rfqT4DEKTOTbnpWDz7LtZJGV13kt7Gd+XhBSU=,tag:fa/+uZPQOTSmyLPpGd3WoQ==,type:str]
    username: ENC[AES256_GCM,data:4QWSknLhoWNDkpku4YJuHQ==,iv:MU1oB8BocaFPpGp/9uPce6SKPvnbZXboEUxnjpXSU2s=,tag:dCq8AyxtjZonbJhSr5Y9yw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitea-credentials
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVkdHUGEyZXQ4T3k5SVhm
            c0JRQnlFUnk4UjJZd2YxYUVjR0d5d2NPQjBFClpKOCtqQ0RjcUlsQmpPTS9WM2Ni
            NlVkT2JhQzRwdysxbnVMdFNhOWxRMHcKLS0tIERSTnNQS2FxRXhGQkhobzlJSWVO
            M00yeEFGaTVMTUNwam84aTRwMVR1REkKU+Fo9N2V80+DKcAKvkS6nh8vQWt5JZ0h
            20zVvy1wzZZWsNtByNcQ2tkliIgCDWQ2t+dZdukqQ8rc1EnY2UzZzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T19:18:19Z"
    mac: ENC[AES256_GCM,data:OoNgr45qW6uIw6cQZkx190IWrQ7g2bFc0Dz54kz1drmXAG2E31/G+fddAjY5sPF/QCi17arZD++fM88Gw/N0hzGUDHYjObpzvr6lTuqXzah9BFxjqz9TsMws/2IqF1q4PwP+iqzXpoQpie0WkFKUf3xYaOYno+r7japINncFR3U=,iv:4JLTDe7h8vYEehxOlLdLMq44KriDlt1MjPg0QNXU4FA=,tag:5oUT3FEQyf9zt+Uy2Hc2Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
