---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: gitea
      version: '11.0.1'
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
  values:
    image:
      registry: docker.gitea.com
      repository: gitea
      tag: '1.23.7'
      rootless: true
    service:
      ssh:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: gitea-ssh.cluster.dnhrrs.xyz
        type: LoadBalancer
    ingress:
      enabled: true
      className: nginx-internal
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: 16m
      hosts:
        - host: gitea.cluster.dnhrrs.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-cert
          hosts:
            - gitea.cluster.dnhrrs.xyz
    persistence:
      enabled: true
      create: false
      claimName: gitea
    gitea:
      admin:
        existingSecret: gitea-credentials
      config:
        server:
          SSH_DOMAIN: gitea-ssh.cluster.dnhrrs.xyz
        database:
          DB_TYPE: postgres
          HOST: postgresql-16-rw.database.svc.cluster.local:5432
          NAME: gitea
          USER: gitea
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
    redis:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/redis
        tag: 7.4.3-debian-12-r0@sha256:a25b5d07a14ec13730022c7cd9bab6308d55ccd86b74af7315553c17be884889
  valuesFrom:
    - kind: Secret
      name: gitea-credentials
      valuesKey: database
      targetPath: gitea.config.database.PASSWD
