---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: echo-server
      version: '0.5.0'
      sourceRef:
        kind: HelmRepository
        name: ealenn
        namespace: flux-system
  values:
    image:
      repository: ealen/echo-server
      tag: '0.9.2'
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: echo.cluster.dnhrrs.xyz
          paths:
            - /
