---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: echo-server
      version: '0.5.0'
      sourceRef:
        kind: HelmRepository
        name: ealenn
        namespace: flux-system
  values:
    image:
      repository: ealen/echo-server
      tag: '0.9.2@sha256:006b92e1d6682442e29d1d0d73c34a61166d42f8a5bf1ea10c318f07ad4790e2'
    ingress:
      enabled: true
      ingressClassName: nginx-internal
      hosts:
        - host: echo.cluster.dnhrrs.xyz
          paths:
            - /
