---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/home/emqx/app
  prune: true
  wait: true
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: homelab
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: emqx
      CAPACITY: 1Gi
      STORAGE_CLASS: local-hostpath
