---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/home/emqx/app
  prune: true
  wait: true
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: homelab

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-volsync
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/volsync-system/volsync/template
  prune: false
  wait: true
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: homelab
  postBuild:
    substitute:
      APP: emqx
      CAPACITY: 1Gi
