---
- name: Create Proxmox VM
  delegate_to: localhost
  proxmox_kvm:
    api_user: "{{ proxmox_api['user'] }}"
    api_token_id: "{{ proxmox_api['token_id'] }}"
    api_token_secret: "{{ proxmox_api['token_secret'] }}"
    api_host: "{{ proxmox_api['host'] }}"
    name: "{{ proxmox_name }}"
    node: "{{ proxmox_node }}"
    pool: "{{ proxmox_pool }}"
    cores: "{{ proxmox_cores }}"
    memory: "{{ proxmox_memory }}"
    net:
      net0: 'virtio,bridge=vmbr0,tag=20'
    scsi:
      scsi0: "{{ proxmox_cd }}"
    virtio:
      virtio0: "local-lvm:{{ proxmox_disk }},format=raw"
    bootdisk: virtio0
    onboot: true
    state: present
  register: vm_created
  when: proxmox_clone == ""
- name: Wait for VM to create
  delegate_to: localhost
  wait_for:
    timeout: 10
  when: vm_created is changed
