---
- name: Generate name
  delegate_to: localhost
  set_fact:
    proxmox_name: "{{ proxmox_role }}-{{ inventory_hostname | replace('.', '-') }}"

- name: Create VM
  include_tasks: create.yaml
  when: proxmox_clone == ""

- name: Clone VM
  include_tasks: clone.yaml
  when: proxmox_clone != ""

- name: Start Proxmox VM
  delegate_to: localhost
  proxmox_kvm:
    api_user: "{{ proxmox_api['user'] }}"
    api_token_id: "{{ proxmox_api['token_id'] }}"
    api_token_secret: "{{ proxmox_api['token_secret'] }}"
    api_host: "{{ proxmox_api['host'] }}"
    name: "{{ proxmox_name }}"
    node: "{{ proxmox_node }}"
    state: started
- name: Wait for VM to boot
  wait_for_connection:
    timeout: 60
  when: proxmox_clone != ""

- name: Set up DNS records
  import_tasks: dns.yaml
  delegate_to: "{{ groups['dns_authoritative'] | first }}"
  become: true
