---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-chart
  namespace: network
spec:
  interval: 10m
  path: ./kubernetes/apps/network/metallb/chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
