pdns_api_key: ENC[AES256_GCM,data:uUfthzL/F+zKjM+1gAMg+4TW+8C4R6nPcxmj5IP7/NM=,iv:G6Jos71W46rZJiPFrQQOI9UJKOumcxS4L19NlinKK3o=,tag:itjvNwIHe1H7p1BWiB0JxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscUl3M3FieUliVFJ6T1NZ
            dlFFZjBjLzY2ZFNWZlZ4VnMrQTh6TVcyRGpBCjZpWmhDcmdBZ1cxcVg3U2drN005
            K1pMM2diUGJXcHE4Ym13L0NaaXpsUzgKLS0tIExGajdkdDFRZGk3K1FVaURPbm5i
            eEZlRkRZRnlUQVNTbzE2V2w1YUlxUVUKNZkeHS0UxMakdHmRjchuGywlTzjr2KA7
            xbLAXOgQDwnK6CfXHUxHy+ENAcbD6RV0Md/BpccwQfNysuyoS0rZWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T17:34:52Z"
    mac: ENC[AES256_GCM,data:/FAElJP/VfvncoI5j/2UfXo1w4rqiDZpzkpSgkHivr9PEpisBZtrcZ3wx5e6YVq7IZPeKEeRzm6Uqa2SEoQqsjCjj63eIbQKkVHrbimZ1pwiUWwTdfXl18LkjptaMygvPf2zGCOCbrc7gQgiVQGEoKAs//lheC1QgEccFbq+nyU=,iv:7q6NnJvskmo+dgr6iDrD2na5d1l33Pqo8wThch/kbO8=,tag:ieMS4wrrxpyPJw28ZMJhZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
