---
unbound_local_only: false
unbound_allowed_addresses: ['10.23.0.0/16']
unbound_private_domains: ['dnhrrs.xyz']
unbound_private_addresses: ['10.23.0.0/16']
unbound_local_zones:
  10.in-addr.arpa: transparent
unbound_stub_zones:
  dnhrrs.xyz:
    stub_addrs: "{{ groups['dns_authoritative'] }}"
  23.10.in-addr.arpa:
    stub_addrs: "{{ groups['dns_authoritative'] }}"
