---
pdns_api: true
pdns_api_allow_from: ['10.23.0.0/16']
pdns_records:
  - { zone: dnhrrs.xyz, name: ha, type: A, content: 10.23.30.5 }
  - { zone: 23.10.in-addr.arpa, name: '5.30', type: PTR, content: ha.dnhrrs.xyz. }
  - { zone: dnhrrs.xyz, name: api.mercury.k8s, type: A, content: 10.23.20.33 }
  - { zone: 23.10.in-addr.arpa, name: '33.20', type: PTR, content: api.mercury.k8s.dnhrrs.xyz. }
  - { zone: dnhrrs.xyz, name: ingress.mercury.k8s, type: A, content: 10.42.0.10 }
