---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/network/external-dns/app
  prune: true
  wait: true
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: homelab
