---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: edgerouter
  namespace: kube-system
spec:
  peerIP: 10.23.20.1
  asNumber: 64512
---
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
  namespace: kube-system
spec:
  serviceExternalIPs:
    - cidr: 10.42.0.0/24
