---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/volsync-system/volsync/app
  prune: true
  wait: true
  targetNamespace: volsync-system
  sourceRef:
    kind: GitRepository
    name: homelab
