---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photoprism
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: photos
  mountOptions:
    - hard
    - ro
    - rsize=32768
    - wsize=32768
  nfs:
    path: /volume1/Photos
    server: nas.dnhrrs.xyz
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photos
spec:
  storageClassName: photos
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
