---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: woodpecker-server
  namespace: woodpecker
spec:
  interval: 1h
  chart:
    spec:
      chart: woodpecker-server
      version: '0.15.5'
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
  values:
    image:
      repository: 'woodpeckerci/woodpecker-server'
      tag: 'v0.15.11'
      pullPolicy: IfNotPresent
    env:
      WOODPECKER_HOST: https://woodpecker.dnhrrs.xyz
      WOODPECKER_OPEN: 'true'
      WOODPECKER_DATABASE_DRIVER: postgres
      WOODPECKER_GITHUB: 'false'
      WOODPECKER_GITEA: 'true'
      WOODPECKER_GITEA_URL: https://gitea.dnhrrs.xyz
      WOODPECKER_ADMIN: administrator
    extraSecretNamesForEnvFrom:
      - woodpecker-env
      - woodpecker-agent-secret
    persistentVolume:
      enabled: true
      size: 1Gi
      storageClass: nfs-client
    ingress:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
