---
- name: Initialise cluster
  command:
    cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: ~/.kube
    state: directory

- name: Link kubectl config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Install flannel to cluster
  command: "kubectl apply -f {{ kubernetes_flannel_manifest }}"
  register: kubernetes_flannel_result
  changed_when: "'created' in kubernetes_flannel_result.stdout"

- name: Generate join command
  command: 'kubeadm token create --print-join-command'
  changed_when: false
  register: kubernetes_join_command

- name: Set join command on all hosts
  set_fact:
    kubernetes_join_command: "{{ kubernetes_join_command }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['kubernetes'] }}"
