---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pairdrop
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/pairdrop/app
  prune: true
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab
