---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/prometheus-operator-crds/app
  prune: true
  wait: true
  targetNamespace: monitoring
  sourceRef:
    kind: GitRepository
    name: homelab
