---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 1h
  provider: generic
  ref:
    tag: v2.4.0@sha256:456f82fce9bce6dbfbca1ad9f21a4c6f33ee0a35c846de1fac4a1b9bcdea98a7
  url: oci://ghcr.io/fluxcd/flux-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1h
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-manifests
