---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 1h
  provider: generic
  ref:
    tag: v2.4.0
    digest: 'sha256:8a1b40166d6b9575d8ba3987bca8d8cec629c4510cd2b4706bd005c4421b9cf6'
  url: oci://ghcr.io/fluxcd/flux-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1h
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-manifests
