---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 1h
  provider: generic
  ref:
    tag: v2.4.0
    digest: 'sha256:47a5f1919d50a6cbc94cd69a0437332f009a812e7cccf5621dd6ff5477b20b77'
  url: oci://ghcr.io/fluxcd/flux-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1h
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-manifests
