---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/mealie/app
  prune: true
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: mealie
      CAPACITY: 1Gi
      STORAGE_CLASS: local-hostpath
