---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: bookstack
      version: '4.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/bookstack
      tag: version-v21.12
    env:
      APP_KEY:
        valueFrom:
          secretKeyRef:
            name: bookstack-key
            key: key
      DB_HOST: mariadb-primary.mariadb
      DB_USER:
        valueFrom:
          secretKeyRef:
            name: bookstack-credentials
            key: user
      DB_PASS:
        valueFrom:
          secretKeyRef:
            name: bookstack-credentials
            key: password
      DB_DATABASE: bookstack
      APP_URL: https://bookstack.dnhrrs.xyz
      AUTH_METHOD: saml2
      SAML2_NAME: SSO
      SAML2_EMAIL_ATTRIBUTE: email
      SAML2_EXTERNAL_ID_ATTRIBUTE: uid
      SAML2_DISPLAY_NAME_ATTRIBUTES: Name
      SAML2_IDP_ENTITYID: https://auth.dnhrrs.xyz/api/v3/providers/saml/1/metadata/?download
      SAML2_AUTOLOAD_METADATA: true
      APP_DEBUG: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: nginx
        hosts:
          - host: bookstack.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: bookstack-cert
            hosts:
              - bookstack.dnhrrs.xyz
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: bookstack
