apiVersion: v1
data:
    WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:fVR4zUzLKbE81glrkf0UruYClp0kWhDQ8P6nl8qVS5oVmTox/mzHhlSHiXk=,iv:sBo24uPUaPglssFQID2P+/TcBB+tircMHf9n7iweQIo=,tag:xJuv3joDUKtBae2Skem+Qw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: woodpecker-agent-secret
    namespace: woodpecker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZGFEM3VzNHRRL0xQa0lF
            TDhPM0lNb3lOZGc3aE9uR1lKVllWUkJuQTJVCnlBemVkaHJFNGlOTjRBMmRpSThF
            NHZvUGVDL0FaZkl5cUw2OHJFd0hBdk0KLS0tIE5KVnNyZlpoMnFmbklCZzladUV2
            T1RUTDdKZ2orRm13SXlxa1ZRYlQ2UVEKk5R6ZPYfDb2DWUwTnLEmkVLG+fBm1WfH
            JRWLTHj5AZNyAOc6exmFuPcn26Qj1sQbErljAITczx1nub4/vVDxIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T11:20:25Z"
    mac: ENC[AES256_GCM,data:acvYiV+zHwCMKNpND678BmYuUEcj+1FGCAD6Q1EtG4dlLvgLlMAlD7PT5xoYAXsEtpTPgF17uCN7xprWAhT0bF1ZCvZDBWdfYArp1IKcKsEEFd9U4ib0dWON2QWMPoawp16bR8IlUq+Mtw6A788bubdoiu/1Vi2XAsVLp+Ase5U=,iv:Y8kecUDfByISLKXE4+OufQ/HR5Nj+0PBS4rQlo0b7s8=,tag:lZ2Jvp34YTmyVGWqlQDxIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
