---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/openebs-system/openebs/app
  prune: true
  wait: true
  targetNamespace: openebs-system
  sourceRef:
    kind: GitRepository
    name: homelab
