---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yml
configMapGenerator:
  - name: node-red-config
    files:
      - config/settings.js
generatorOptions:
  disableNameSuffixHash: true
