---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/home/zigbee2mqtt/app
  prune: true
  wait: true
  targetNamespace: home
  sourceRef:
    kind: GitRepository
    name: homelab
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: zigbee2mqtt
      CAPACITY: 1Gi
      STORAGE_CLASS: local-hostpath
