---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '3.4.0'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      node-red:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: nodered/node-red
              tag: 4.0.3
            envFrom:
              - secret: node-red-credentials
    service:
      app:
        controller: node-red
        ports:
          http:
            port: 1880
    ingress:
      app:
        className: nginx
        hosts:
          - host: nodered.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: node-red
      config:
        type: configMap
        name: node-red-config
        globalMounts:
          - path: /data/settings.js
            subPath: settings.js
            readOnly: true
