apiVersion: v1
kind: Secret
metadata:
    name: gitea-credentials
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:+2Q76C1MCcC4Z5g=,iv:rYsOGN3hNhZJNO3vz18WFOu7nqT5dv4PzH1xz6WR+64=,tag:ZMKLvmWoHNEdcTUbOM6kBg==,type:str]
    password: ENC[AES256_GCM,data:SZJdOgPaH73Bm8DyyhryC10Ze1b6GF6bOewAH/UpymI=,iv:Bn3ofYxyswWil4EBEuXwOhb/nYAda//q4FW+x2RT3/s=,tag:3r4WlwiqGIe1pjN+ekkz3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-10-15T14:48:03Z'
    mac: ENC[AES256_GCM,data:+MjzPdFHzIgV7Kh03exoBk4WN/+DXjiDvIVbrGDtQOhu0AOq2vqxQF4Zsaq+Twe3z3+LGAz1R7PiR/Ah6zsmjXOrflWg7wQ4t2mDTnN4CE3KFtxWRO40IkLRubpaxNYW5RSyYrcEE6DDhRQpn3SWIGt4Zm5rGRw/mrLV9FvL9c8=,iv:tz1aQYRfMr+SQXJ6PJckFM9RvoAJ/cbzsjsQ6Cnb3+A=,tag:GliUEiUQbUHIc6hcOolFAA==,type:str]
    pgp:
    -   created_at: '2022-10-15T13:48:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxlxznDH90E6AQ/8DXNRhn/nJNXquzWTiQe1EQdB5oRp7MQ2bRpt5jntKAks
            W8WsngfGeJw31Busbd/lUIOfZ6jvYtyrnIjFbT3IVofZOmojPhBSQkC110mOlXpn
            tVujFIFEgu2WReZo1eDNwKMbU9GO6cz9TVJVuW0GVfqg3basCMQTE/LrtJ5m/nve
            W+RDvnfBNomAaDw8sO12I1t324BOYbXP6veaNTrpam7qQS2t6ZcGCKXMSHqeEIfR
            bl8UnkZHfpNwqu0dM1pLhMqeU1NoJ9iTTNFZ1oMy384QzKJciy+qKyM4GgYPCLjZ
            uovQfrjV0lzS2BlJNOg2uUAChGXEvIzQfXYwVssD7/5MEG8mEG4mDN67jJ7MZZ29
            gqgVV4NterRiO3CVyWjhkKixOOfZrLujlbpcVU+SUb7pvBn10viztOSHSvfs9a/V
            gYZPd0Ad691nJVSoE/NwUZk4nTfBzgivm4WuRdeQYIYLUpYe9cz3dh53OXbSPLhf
            dy+BXhN4y8jaJ1OKfX+JB3XvTr11Ah4bF8HyFgf+U4h5WREFAPSvFb8LD6X/7cUX
            IODTjUWztCnmYKvQe7QTkmEjh3no9U60wNWH59x3FIBbfkiK5wONGiSgvHkrDdzc
            P2hvKwPU6EPzdtDkWJbeIGyHxnnSJJS2cBUpW+g6yRtilhNHbtyou6egLhrFT8/S
            XgE9tmCk5rGls6n6UkkDG2yLUHbmS4AoDllQvJXAEy7cwaB3WfQtAQPQP0pxitSA
            oEgFj8zoHshrLppBnFpSibRk9b2MSp+jQ/0Khg2NVtSEFGvT+pWyTeEZbpfuGMo=
            =7ASp
            -----END PGP MESSAGE-----
        fp: 027AF72E69902FFABC4EC908C5C4837CA36C0020
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
