---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-app
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/database/cloudnative-pg/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/database/cloudnative-pg/cluster
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: cloudnative-pg-app
