clusterName: mercury
talosVersion: v1.1.1
kubernetesVersion: v1.24.12
endpoint: https://api.mercury.k8s.dnhrrs.xyz:6443
domain: cluster.local
allowSchedulingOnMasters: false
additionalMachineCertSans:
  - api.mercury.k8s.dnhrrs.xyz
clusterPodNets:
  - 192.168.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: custom
  urls:
    - https://docs.projectcalico.org/archive/v3.20/manifests/calico.yaml
nodes:
  - hostname: talos-10-23-20-36
    ipAddress: 10.23.20.36
    installDisk: /dev/vda
    controlPlane: true
    nameservers:
        - 10.23.20.41
        - 10.23.10.2
    networkInterfaces:
        - interface: eth0
          addresses:
              - 10.23.20.36/24
          routes:
              - network: 0.0.0.0/0
                gateway: 10.23.20.1
          vip:
              ip: 10.23.20.33
  - hostname: talos-10-23-20-12
    ipAddress: 10.23.20.12
    installDisk: /dev/sda
    controlPlane: false
    nameservers:
        - 10.23.20.41
        - 10.23.10.2
    networkInterfaces:
        - interface: eth0
          addresses:
              - 10.23.20.12/24
          routes:
              - network: 0.0.0.0/0
                gateway: 10.23.20.1
  - hostname: talos-10-23-20-37
    ipAddress: 10.23.20.37
    installDisk: /dev/vda
    controlPlane: false
    nameservers:
        - 10.23.20.41
        - 10.23.10.2
    networkInterfaces:
        - interface: eth0
          addresses:
              - 10.23.20.37/24
          routes:
              - network: 0.0.0.0/0
                gateway: 10.23.20.1
