---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: woodpecker-agent
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: woodpecker-agent
      version: '0.15.5'
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: 'woodpeckerci/woodpecker-agent'
      tag: 'v0.15.5'
      pullPolicy: IfNotPresent
    env:
      WOODPECKER_SERVER: woodpecker-server.default.svc.cluster.local:9000
      WOODPECKER_LOG_LEVEL: debug
    extraSecretNamesForEnvFrom:
      - woodpecker-agent-secret
