---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - _namespace.yaml
  - renovate-env.yaml
  - cron.yaml
configMapGenerator:
  - name: renovate-config
    namespace: renovate
    files:
      - config.json
