apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ZrBCpsoLPkliE5X4sNcCsTWfbkrPeqAbq9c7qzqTUo4pWKvCkOOyFoBwBJtCbC/7IGmdzn/uhjs=,iv:nupaU1Kzw3kNfU2wNfs2VfkTe29E0p1eJo+7qv5z66o=,tag:YCqMsWCyJfnuQWXfhXABcA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-env
    namespace: renovate
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRkk1RnQreDBhSlV6NDdI
            SlZiUFZ0eDVmN0QxZkt0cGpHMFZCM1h2dUFrCkFyMDQ2dE9Zblg5cGt4bkpHOGh5
            L29kNmVIUUY0QitNcXAxK3dxc2xkR0EKLS0tICtkTVgxTkI0Z3hlWTU3TDR5VmF3
            TFJobjRtNWxoRmx2clZxSWY5R0hnYVUKl1VsKnf8XWh6/c7NcOI0ngBsqEH/7oVc
            p97RIf8HNd/z6xdCw3R/RsqilYZPdm+vkpZsrKgU9MeiCpXtUaO9Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-12T18:11:10Z"
    mac: ENC[AES256_GCM,data:cIYzByDWH3Wt2TmUP+eV3EeH6uT5uNzFTv+nGwB2e4JSOu/jEPTw/EjoSQZMpmD2YiaIv8aVS2BrD45SkatZx0BmImHkY7toGk3islJq4yWzSaGfIxliZfim/w4q/Hf6M68wjDzpmHDQri8Rb0OJzGYIbdp6rh3/qdK9aP5NR4U=,iv:w6TV/RFyyhnOp+ZHquk85t9g04xROTlnGvKA+NKJufg=,tag:u25FDBSuE/KsuGAQ/UoQzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
