---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-server
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/network/echo-server/chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
