---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.13.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    fullnameOverride: ingress-nginx-internal
    controller:
      image:
        registry: registry.k8s.io
        image: ingress-nginx/controller
        tag: "v1.10.0"
      config:
        force-ssl-redirect: 'true'
        hide-headers: Server,X-Powered-By
        enable-brotli: 'true'
        enable-ocsp: 'true'
        block-user-agents: GPTBot,~*GPTBot*,ChatGPT-User,~*ChatGPT-User*,Google-Extended,~*Google-Extended*,CCBot,~*CCBot*,Omgilibot,~*Omgilibot*,FacebookBot,~*FacebookBot*
        ssl-protocols: TLSv1.3 TLSv1.2
      allowSnippetAnnotations: true
      publishService:
        enabled: false
      extraArgs:
        default-ssl-certificate: network/cluster-dnhrrs-xyz-cert
        publish-status-address: internal.cluster.dnhrrs.xyz
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: internal.cluster.dnhrrs.xyz
      ingressClassResource:
        name: nginx-internal
