---
- name: Install unbound
  ansible.builtin.package:
    name: unbound
    state: present

- name: Install unbound config
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    mode: '0644'
  notify: Restart unbound

- name: Enable unbound service
  ansible.builtin.service:
    name: unbound
    state: started
    enabled: true
