---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-chart
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/cert-manager/cert-manager/chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/cert-manager/cert-manager/issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: cert-manager-chart
