---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - repos/ingress-nginx.yaml
  - repos/jetstack.yaml
  - repos/nfs-subdir-external-provisioner.yaml
