---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/grafana/app
  prune: true
  wait: true
  targetNamespace: monitoring
  sourceRef:
    kind: GitRepository
    name: homelab
