---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: tf-controller
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
  values:
    image:
      tag: v0.14.1
    runner:
      image:
        tag: v0.14.1
