---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yml
  - photos.yml
configMapGenerator:
  - name: photos-web
    namespace: default
    files:
      - settings.json
