---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.11.2'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      image:
        registry: registry.k8s.io
        image: ingress-nginx/controller
        tag: "v1.10.0"
      config:
        force-ssl-redirect: 'true'
      allowSnippetAnnotations: true
      extraArgs:
        default-ssl-certificate: network/cluster-dnhrrs-xyz-cert
