---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.12.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      image:
        registry: registry.k8s.io
        image: ingress-nginx/controller
        tag: "v1.10.0"
      config:
        force-ssl-redirect: 'true'
      allowSnippetAnnotations: true
      publishService:
        enabled: false
      extraArgs:
        default-ssl-certificate: network/cluster-dnhrrs-xyz-cert
        publish-status-address: internal.cluster.dnhrrs.xyz
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: internal.cluster.dnhrrs.xyz
