---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.22.1'
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    crds:
      create: true
