---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '3.6.1'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.1.1@sha256:c7b111384716247f057b449ebb242bf05f3fafb98dd6d5688c1ac1fc730d5e95
            env:
              TZ: Europe/London
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyACM0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ember
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx.home.svc.cluster.local:1883
              ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
              ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: true
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true
            envFrom:
              - secret: zigbee2mqtt-credentials
            securityContext:
              fsGroup: 1000
              privileged: true
    service:
      app:
        controller: app
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: nginx
        hosts:
          - host: zigbee.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: zigbee2mqtt
      usb:
        type: hostPath
        hostPathType: CharDevice
        hostPath: /dev/ttyACM0
        globalMounts:
          - path: /dev/ttyACM0
