---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/paperless-ngx/app
  prune: true
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx-volsync
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/volsync-system/volsync/template
  prune: true
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab
  postBuild:
    substitute:
      APP: paperless-ngx
      CAPACITY: 1Gi
