---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/default/paperless-ngx/app
  prune: true
  wait: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: paperless-ngx
      CAPACITY: 1Gi
      DELAY: "2"
      STORAGE_CLASS: local-hostpath
