---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: '6.17.3'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    image:
      repository: grafana/grafana
      tag: 9.1.2
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      hosts:
        - grafana.dnhrrs.xyz
      tls:
        - secretName: grafana-cert
          hosts:
            - grafana.dnhrrs.xyz
    persistence:
      enabled: true
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      size: 1Gi
    initChownData:
      enabled: false
    admin:
      existingSecret: grafana-credentials
      userKey: admin-user
      passwordKey: admin-password
