---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: '6.17.3'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    image:
      repository: grafana/grafana
      tag: 10.1.1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      hosts:
        - grafana.dnhrrs.xyz
      tls:
        - secretName: grafana-cert
          hosts:
            - grafana.dnhrrs.xyz
    persistence:
      enabled: true
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      size: 1Gi
    initChownData:
      enabled: false
    admin:
      existingSecret: grafana-credentials
      userKey: admin-user
      passwordKey: admin-password
    envFromSecret: grafana-env
    grafana.ini:
      server:
        root_url: https://grafana.dnhrrs.xyz
      auth:
        signout_redirect_url: https://auth.dnhrrs.xyz/if/session-end/grafana/
        oauth_auto_login: true
        oauth_allow_insecure_email_lookup: true
      auth.generic_oauth:
        enabled: true
        name: authentik
        client_id: 27b98580d3a21b6392d35d703198f1a2beb16b5d
        scopes: openid profile email
        auth_url: https://auth.dnhrrs.xyz/application/o/authorize/
        token_url: https://auth.dnhrrs.xyz/application/o/token/
        api_url: https://auth.dnhrrs.xyz/application/o/userinfo/
        role_attribute_path: "contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
