---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/storage/democratic-csi/app
  prune: true
  wait: true
  dependsOn:
    - name: snapshot-controller
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: homelab
