---
- hosts: dns_record
  gather_facts: false
  become: false
  serial: 1
  tasks:
    - name: Register A record in DNS
      delegate_to: localhost
      uri:
        url: "http://{{ groups['dns_authoritative'][0] }}:8081/api/v1/servers/localhost/zones/dnhrrs.xyz."
        method: PATCH
        headers:
          X-API-Key: "{{ pdns_api_key }}"
        body_format: json
        body:
          rrsets:
            - name: "{{ dns_name }}.{{ dns_zone }}.dnhrrs.xyz."
              type: A
              ttl: 3600
              changetype: REPLACE
              records:
                - content: "{{ inventory_hostname }}"
        status_code: [204]
    - name: Register PTR record in DNS
      delegate_to: localhost
      uri:
        url: "http://{{ groups['dns_authoritative'][0] }}:8081/api/v1/servers/localhost/zones/23.10.in-addr.arpa."
        method: PATCH
        headers:
          X-API-Key: "{{ pdns_api_key }}"
        body_format: json
        body:
          rrsets:
            - name: "{{ inventory_hostname.split('.') | reverse | join('.') }}.in-addr.arpa."
              type: PTR
              ttl: 3600
              changetype: REPLACE
              records:
                - content: "{{ dns_name }}.{{ dns_zone }}.dnhrrs.xyz."
        status_code: [204]
