---
- hosts: proxmox_vm
  gather_facts: false
  become: false
  serial: 1
  tasks:
    - name: Generate name
      delegate_to: localhost
      set_fact:
        proxmox_name: "{{ proxmox_role }}-{{ inventory_hostname | replace('.', '-') }}"
    - name: Stop Proxmox VM
      delegate_to: localhost
      proxmox_kvm:
        api_user: "{{ proxmox_api['user'] }}"
        api_password: "{{ proxmox_api['password'] }}"
        api_host: "{{ proxmox_api['host'] }}"
        name: "{{ proxmox_name }}"
        node: "{{ proxmox_node }}"
        state: stopped
        force: true
      register: vm_stopped
      ignore_errors: true
    - name: Wait for VM to stop
      delegate_to: localhost
      wait_for:
        timeout: 10
      when: vm_stopped is changed
    - name: Destroy Proxmox VM
      delegate_to: localhost
      proxmox_kvm:
        api_user: "{{ proxmox_api['user'] }}"
        api_password: "{{ proxmox_api['password'] }}"
        api_host: "{{ proxmox_api['host'] }}"
        name: "{{ proxmox_name }}"
        node: "{{ proxmox_node }}"
        state: absent
      when: vm_stopped is not failed
    - name: Add to dns_record group
      add_host:
        hostname: "{{ inventory_hostname }}"
        groups:
          - dns_record
      changed_when: false

- name: Delete DNS records
  import_playbook: destroy-dns.yaml
  vars:
    dns_name: "{{ proxmox_name }}"
