---
- hosts: all
  tags: common
  roles:
    - role: jnv.unattended-upgrades
      tags: [updates]

- hosts: dns_authoritative
  roles:
    - role: pdns
      tags: [dns]

- hosts: dns_recursive
  roles:
    - role: unbound
      tags: [dns]
