---
- hosts: proxmox_vm
  gather_facts: false
  become: false
  serial: 1
  tags: vm
  roles:
    - proxmox

- hosts: all:!talos
  tasks:
    - name: Automatic updates on debian
      include_role:
        name: jnv.unattended-upgrades
      tags: [updates]
      when: ansible_facts['os_family'] == 'Debian'

- hosts: dns_authoritative
  roles:
    - role: pdns
      tags: [dns]

- hosts: dns_recursive
  roles:
    - role: unbound
      tags: [dns]

- hosts: k8s_nfs
  roles:
    - geerlingguy.nfs

- hosts: wireguard
  roles:
    - ipr-cnrs.nftables
  tasks:
    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
