---
- hosts: all
  tags: common
  roles:
    - role: jnv.unattended-upgrades
      tags: [updates]

- hosts: dns_authoritative
  roles:
    - role: pdns
      tags: [dns]

- hosts: dns_recursive
  roles:
    - role: unbound
      tags: [dns]

- hosts: mysql
  pre_tasks:
    - name: Install python interpreters
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "python-pymysql"
        - "python3-pymysql"
  roles:
    - role: geerlingguy.mysql
      tags: [database, mysql]
