---
- hosts: proxmox_vm
  gather_facts: false
  become: false
  serial: 1
  tags: vm
  roles:
    - proxmox

- hosts: debian
  tags: common
  roles:
    - role: jnv.unattended-upgrades
      tags: [updates]

- hosts: dns_authoritative
  roles:
    - role: pdns
      tags: [dns]

- hosts: dns_recursive
  roles:
    - role: unbound
      tags: [dns]

- hosts: nfs
  roles:
    - geerlingguy.nfs
