---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  interval: 1h
  chart:
    spec:
      chart: mariadb
      version: '11.0.13'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/mariadb
      tag: 10.6.8-debian-11-r3
    architecture: replication
    auth:
      existingSecret: mariadb-credentials
    primary:
      persistence:
        storageClass: nfs-client
    secondary:
      replicaCount: 1
      persistence:
        storageClass: nfs-client
