apiVersion: v1
data:
    mariadb-password: ENC[AES256_GCM,data:C7tmb/kkdfI7Ocd/LI8svBHAYYI7mCLa,iv:9ql3QGRsiJtLFNzyUQYWe6UDU7wG+S6rhY3DbiEqW9Y=,tag:ulamodB6fejL3jkXkT2apA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:oZQAkrH7wS9jsnWI2i14yt8ubOKZkEjL,iv:mdXcB01QW2QvxrZKcgDUF3w6dEi/69VMorgzNm/QPbo=,tag:wDTVxo4Mj/HRIG24wTnd0A==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:4Ojwbd8ffp8ApjDLOAXx4jTo4noC0M6X,iv:wry+NAC/CuBEi+gnX6IhAJkLbSufojKpFCWlhblwWn4=,tag:vDkjn3JbFTrStAgWlEwD5Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: mariadb-credentials
    namespace: mariadb
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-06-17T13:13:32Z'
    mac: ENC[AES256_GCM,data:sKIh/JTIxqcF9XJK6pqXKqWXD9UwR1tUVVDOjfELo8uYi/cM8182iGqQbImK/vfJvI0PQ+Tl+o/7X7+rFO0dnSQ+eZhuDd/pe4sdow8BBgTl0HjtZSD/PA7BJSYYIECbIFrvOF+cXnTB0c/Pfq4mTX54Jknh+YCwDe3hfEIRO0Q=,iv:ic9nXQUMckEZlwooED5NIO9rhqqxapBsUYtPWX/ksd8=,tag:8kLleOVXvpiKZ/ruV8Ny5w==,type:str]
    pgp:
    -   created_at: '2022-06-17T13:13:31Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxlxznDH90E6ARAA4xHQT9bdl/Mw5OJOWJ9Zo9xuViwF1ilfwljQzlVnaJ9E
            ZHvnSJs6EdUKZl8ddTYIbeAYUIKwuFXDHJwbLquAy76vl/5UCccXvOUHNmxLaFwk
            UcIfR0cDQqxFIYjwo4cVVgb35jYTmQdozbyW7qA1thur+dMpLghQ47FZKwnw9cGN
            uio+YIOGkPFDqRrZyHbTOyKrsoVjqHWuqX19l701m2hwnXj9P61UH71N0is7///s
            msWCfcFh8VukgezFNIs2RfZuGBavHr7X3wtt3DzTWaIOypXEPp9OLZmuaXZSYiv0
            eCf1lACrnq5VMtbwMeV2cFTqXxRvFdM0egM6xVhUX0hOVNtacAacHK3TRkHOMGiw
            NBKcFnlwmmcnu11rwm1PvdR5M3ddyo5xAFkKCC9Be9jnICo91eyARv2FgEP93IWD
            +LqIvnXbBEzhY7Oeme14HdqAe0J7iR2ZmKZLgdXXk+/gCKf/qKWkj4qvcNjgigYK
            7V073jvME8jMJXkWs8zCZN3lxE9GQxwAq+uSENQcQMJHvwUegBntDfAHyaRHjBym
            KW3ud69OKjTdKVHZHBS42R3GNfouPvJsC38REi01hDvqKv+6YeRnhqfWDP1qeiQ2
            DWJKsDlI7e9bK9EtA6uRhEJ4Cl1wW7Og2OCKtsoemkXV8hEwNAJlT4Q/VY3sxKjS
            XgGr0SWwzYBylu7uvFxPtZwyw8+55iFHXZcj1gUjrd6A8oMhf6McGObxspyGb4x+
            GHS9xhvVBKljfVK+E2acSYIvnXwdWgh1GH7tIZLPMV+TRQi1AJdGM+2QvEWwXz0=
            =1yod
            -----END PGP MESSAGE-----
        fp: 027AF72E69902FFABC4EC908C5C4837CA36C0020
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
