---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.13'
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  values:
    image:
      repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
      tag: 'v4.0.2'
    storageClass:
      defaultClass: true
      name: nfs-client
    nfs:
      server: united-ant.vm.dnhrrs.xyz
      path: /srv/provisioner
      mountOptions:
        - rw
        - hard
        - rsize=32768
        - wsize=32768
