---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: '1.14.4'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
    installCRDs: true
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.14.4
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.14.4
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.14.4
