---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-gateway
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/network/k8s-gateway/chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
