---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pairdrop
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '4.3.0'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: ghcr.io/schlagmichdoch/pairdrop
              tag: v1.11.2@sha256:c4b30977264a76e335740089e693a52a0d0d616330dec7f93c7b96beef7b4a02
            env:
              TZ: Europe/London
    service:
      app:
        controller: app
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: nginx-internal
        hosts:
          - host: pairdrop.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /root/.npm/_cacache
      logs:
        type: emptyDir
        globalMounts:
          - path: /root/.npm/_logs
