---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '4.2.0'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.3.2@sha256:d51ae3b5051439844c1bbe437fb7edffa0826cb9988b366e17ffc7170a8d5ed2
            env:
              TZ: Europe/London
              MAX_WORKERS: '1'
              WEB_CONCURRENCY: '1'
              BASE_URL: https://mealie.cluster.dnhrrs.xyz
              DB_ENGINE: postgres
              POSTGRES_SERVER: postgresql-16-rw.database.svc.cluster.local
              POSTGRES_PORT: '5432'
              POSTGRES_DB: mealie
              OIDC_AUTH_ENABLED: 'true'
              OIDC_CONFIGURATION_URL: https://auth.cluster.dnhrrs.xyz/application/o/mealie/.well-known/openid-configuration
              OIDC_PROVIDER_NAME: Authentik
            envFrom:
              - secret: mealie-credentials
    service:
      app:
        controller: app
        ports:
          http:
            port: 9000
    ingress:
      app:
        className: nginx-internal
        hosts:
          - host: mealie.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: mealie
        globalMounts:
          - path: /app/data
      nltk-data:
        type: emptyDir
        globalMounts:
          - path: /nltk_data
