---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 6.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/external-dns
      tag: 0.10.2-debian-10-r89
    provider: pdns
    pdns:
      apiUrl: http://10.23.20.104
      apiPort: '8081'
      secretName: pdns-credentials
    txtOwnerId: mercury
