---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: '11.7.3'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      repository: bitnami/postgresql
      tag: 14.5.0-debian-11-r3
    architecture: standalone
    auth:
      existingSecret: postgresql-credentials
    primary:
      persistence:
        storageClass: nfs-client
