---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: linkwarden
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: linkwarden
          image: 'ghcr.io/linkwarden/linkwarden:v2.5.3'
          imagePullPolicy: IfNotPresent
          env:
            - name: NEXTAUTH_URL
              value: https://links.cluster.dnhrrs.xyz/api/v1/auth
            - name: NEXT_PUBLIC_AUTHENTIK_ENABLED
              value: 'true'
            - name: AUTHENTIK_ISSUER
              value: https://auth.cluster.dnhrrs.xyz/application/o/linkwarden
            - name: HOME
              value: /data/data
            - name: NEXT_PUBLIC_DISABLE_REGISTRATION
              value: 'true'
            - name: NEXT_PUBLIC_CREDENTIALS_ENABLED
              value: 'false'
          envFrom:
            - secretRef:
                name: linkwarden-env
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: data
              mountPath: /data/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkwarden

---
kind: Service
apiVersion: v1
metadata:
  name: linkwarden
  namespace: default
spec:
  selector:
    app: linkwarden
  ports:
    - name: http
      port: 80
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: linkwarden
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: links.cluster.dnhrrs.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linkwarden
                port:
                  name: http
  tls:
    - secretName: linkwarden-cert
      hosts:
        - links.cluster.dnhrrs.xyz
