---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: '3.5.1'
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      app:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        initContainers:
          playwright-install:
            image: &image
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.7.1
            env:
              HOME: &home /home/linkwarden
            command: ['npx', 'playwright', 'install']
        containers:
          app:
            image: *image
            env:
              NEXTAUTH_URL: https://links.cluster.dnhrrs.xyz/api/v1/auth
              NEXT_PUBLIC_AUTHENTIK_ENABLED: true
              AUTHENTIK_ISSUER: https://auth.cluster.dnhrrs.xyz/application/o/linkwarden
              HOME: *home
              NEXT_PUBLIC_DISABLE_REGISTRATION: true
              NEXT_PUBLIC_CREDENTIALS_ENABLED: false
            envFrom:
              - secret: linkwarden-env
    service:
      app:
        controller: app
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: nginx
        hosts:
          - host: links.cluster.dnhrrs.xyz
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: linkwarden
        globalMounts:
          - path: /data/data
      next-cache:
        type: emptyDir
        globalMounts:
          - path: /data/.next/cache
      home:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-csi
        globalMounts:
          - path: *home
