apiVersion: v1
kind: Secret
metadata:
    name: emqx-credentials
stringData:
    password: ENC[AES256_GCM,data:lfTJPrx39QOZVxe+i/QHG48R5LxeBbMP,iv:LT4X5ie2p0v0Kj2uCW4gV6boLpJg6BxRydIIjkOyP+g=,tag:EZ3hY1q2WGjV0vPl1sQw7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUEc5WHZ0Ti9tblRVdjJm
            YVBsak40SG52V2tTeTdMVU52NUdMYngyNW1vClFkRjVkdTRNY2JnTzBkbGRCcXU3
            bmRyQnJRSERqYmp4cDhKUzQ3Tms2YzAKLS0tIGVJWWdHSXlVdEtNaVZIY25NNU1u
            Z1RXVUlkdGtXRTVwbm5sWlVMbDh6YmsK86rytmtQoCuh3NU0aMj8yDESScrIWMLv
            z5r0PSoisqDyBlsCLs4hFFKGe4m299Y4cIuWGp08rKF4YXM1qp5UIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T19:53:48Z"
    mac: ENC[AES256_GCM,data:c47/xxoi/OtS6TibTSoLTQ8MfZrmBeGTOE/FvaHoEIOGBYmLpZz/Si20ts/YX6XLpUgc2C4PO07TxCAxPD/pnJr6jb14mI6Dfmru1BdE5+9Dc2oB5jRMxl5MZNG03YtRuY83VLZVk6FX8FwLcKMaKKSedDnYjMVZDYaZ42B4Wdg=,iv:eOOI7X4i+kvs6J+xBE9gq7Z8D/d60WyNoui898tTbAs=,tag:ULKbaqchMQ/GsWKDGpRUOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
