---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
spec:
  interval: 1h
  chart:
    spec:
      chart: emqx
      version: '5.8.5'
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  values:
    replicaCount: 1
    persistence:
      enabled: true
      existingClaim: emqx
    emqxConfig:
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
    service:
      type: LoadBalancer
      annotations:
        coredns.io/hostname: emqx-mqtt.cluster.dnhrrs.xyz
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        hosts:
          - emqx.cluster.dnhrrs.xyz
        pathType: Prefix
  valuesFrom:
    - kind: Secret
      name: emqx-credentials
      valuesKey: password
      targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
