---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.0.3'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      image:
        repository: ingress-nginx/controller
        tag: v1.0.2
      service:
        externalIPs:
          - 10.42.0.10
