apiVersion: v1
data:
    password: ENC[AES256_GCM,data:vxIlZ5PbEZXYQHT0ocvI5mHQQu8VjL4G,iv:q1iHIB/QhVWKP8jcy9uSPF5AOJEH+K1cjoQDs83j8jc=,tag:QVuLwe7baToEipTZWquSyA==,type:str]
    username: ENC[AES256_GCM,data:j7KOyeOnBSI=,iv:SX5tsqR6ig56hXASfSlBJ+BcYW7T/KvHz7eEqH7tukM=,tag:/OIaCQfxOIxUvvj75NCECQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextcloud-credentials
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c3BoeFhwd08yVjJiaklD
            aUZFQWo1U1k2ZEdPaFR2a21odVZOS3c3UGxZCld3eFlSc2lSVUNIV1FWOVpYd0Yr
            Ly9Yd1pZajNOSUMzVGJ4MzV4blVTTUkKLS0tIGczOTRZZFBYQmN6MkFlRzhsbkE0
            YnJVVFhNWThHSkF5M25HQUFxY0FMRG8KQgevdRapdDobTtiZoQxGTxsVJSXV4+pe
            INMy0HbHY22bX4iBlT+br6VbTIXzFgy1WnX3rN/FQNwWLF0r/hsXKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T10:56:08Z"
    mac: ENC[AES256_GCM,data:qUNhyBk9nYMSZs2kXVcEk95A51VB/nWT20Uk4Zf2bRKit6p9wkN3RQuwfZxvwlyl+3Xu1RcDEHLYPTs5J+5VwhtLhRRHKjQ4wlTcBD2oEeLqNee2gVOTZTDILRNmZbLoFZu7UPYHJlxf1GrfrDztBhA0ZlTHt6/W7uZeWUg+/24=,iv:38//Wrd6coo0MnU6DOc64b01sxrNznTVCRSCCeEO4oM=,tag:pe2oELcI/Xok9W4uUayphg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
