---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: '3.5.21'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    image:
      repository: nextcloud
      flavor: fpm
      tag: '27.0.1-fpm'
      pullPolicy: IfNotPresent
    nginx:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 0.5Gi
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      hosts:
        - host: nextcloud.dnhrrs.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: nextcloud-cert
          hosts:
            - nextcloud.dnhrrs.xyz
    persistence:
      enabled: true
      existingClaim: nextcloud-data
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-postgresql
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: database
    nextcloud:
      host: nextcloud.dnhrrs.xyz
      existingSecret:
        enabled: true
        secretName: nextcloud-credentials
        usernameKey: username
        passwordKey: password
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        runAsNonRoot: true
        readOnlyRootFilesystem: false
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '192.168.0.0/16',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    phpClientHttpsFix:
      enabled: true
    cronjob:
      enabled: true
