apiVersion: v1
data:
    database: ENC[AES256_GCM,data:KGMBaP0sqV7uLKFZ,iv:UZmfgo8UaHc+GRtEjXDwaTMZvUnHR6IYHzgcNstnWPY=,tag:XMwnCt5w97n2ZRU0U/IXbg==,type:str]
    host: ENC[AES256_GCM,data:p3iY5rw7yv/Gr3PvlUjNqZgFFRHxFynMTDRatuQaID8sMm74/QX682sS18hUL71RVSrD1w==,iv:qY/Av+F+BLfW2B1yiako69t3IMHc4FD2KhzbkmzUpyw=,tag:KPbr+bWw86PLadoyo2G8Ow==,type:str]
    password: ENC[AES256_GCM,data:Lha7OP1dTXOZhrZx2R8qhFIwTq8MXC0HtH14+VhN+wbc59qgnV4z3Z4/vpI=,iv:Z2T52h2p60XB/Qm+dhqhG5XkXBcEVPfEHGP59DZ/o2Q=,tag:rTFnzKStavAXeegQZYroUg==,type:str]
    username: ENC[AES256_GCM,data:CpDWkCPnR8JYPTn8,iv:UaoFCWSguaoD3GcOLowiiZTpvAjYJdBhHuzgTp2oEs0=,tag:htbbgiKXgWCWuk7x9Exmfg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextcloud-postgresql
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age162k3jv9wyce4dkly60tu0l9jmme5qa3fmcrknrz6lx54ru2ftgaqcsy5e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZDFCZEc3MDRIRFAxRUhu
            SnFObmZaVVB6bXhybG16Q1VpWlA1WWtNbERnCk95NVpEclViaVRnK2gwdDk3OFo1
            QVhuQytaNUl0cHJaU1FXQWh5ZDAwMGsKLS0tIDc4MlAwNXNSSnV6QmRzckZwdmY2
            eVZQRVlIZDdKaVZhcktaV0Z2T09lbWMKtTRSNPbMqHvk5WN/ROnBSdaZgH9qY5XR
            2e8GBV2p3FrbWdYTh/wu9J+PklNisHIPckP6Gs155u04IGh5g9pvzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T10:55:19Z"
    mac: ENC[AES256_GCM,data:XO0sq62Y2wj/B7hEgMiEjgVysLYU1mCFb68SPWuFxzlq5sDBG/GXeIrfXBr4pIUX7SqL/t3+D0Jz3YesUpJcv7KamG7K7r7PLATmT/geX4MNv5XhX0Unz6JjmaQKK1utxXdb2YTHZ3mp+gc0HWMZVV3i7TPMpBHAccMFqErwl/o=,iv:spJnQAoAIJ5cGTR2ApBfHL431+zeN1Q1QFdtf4bqkPY=,tag:PVzW3M/HQSsh+eLyBo2nsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
